// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'condition.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

const _$ConditionEnumMap = {
  Condition.thunderstormWithLightRain: 200,
  Condition.thunderstormWithRain: 201,
  Condition.thunderstormWithHeavyRain: 202,
  Condition.lightThunderstorm: 210,
  Condition.thunderstorm: 211,
  Condition.heavyThunderstorm: 212,
  Condition.raggedThunderstorm: 221,
  Condition.thunderstormWithLightDrizzle: 230,
  Condition.thunderstormWithDrizzle: 231,
  Condition.thunderstormWithHeavyDrizzle: 232,
  Condition.lightIntensityDrizzle: 300,
  Condition.drizzle: 301,
  Condition.heavyIntensityDrizzle: 302,
  Condition.lightIntensityDrizzleRain: 310,
  Condition.drizzleRain: 311,
  Condition.heavyIntensityDrizzleRain: 312,
  Condition.showerRainAndDrizzle: 313,
  Condition.heavyShowerRainAndDrizzle: 314,
  Condition.showerDrizzle: 321,
  Condition.lightRain: 500,
  Condition.moderateRain: 501,
  Condition.heavyIntensityRain: 502,
  Condition.veryHeavyRain: 503,
  Condition.extremeRain: 504,
  Condition.freezingRain: 511,
  Condition.lightIntensityShowerRain: 520,
  Condition.showerRain: 521,
  Condition.heavyIntensityShowerRain: 522,
  Condition.raggedShowerRain: 531,
  Condition.lightSnow: 600,
  Condition.snow: 601,
  Condition.heavySnow: 602,
  Condition.sleet: 611,
  Condition.lightShowerSleet: 612,
  Condition.showerSleet: 613,
  Condition.lightRainAndSnow: 615,
  Condition.rainAndSnow: 616,
  Condition.lightShowerSnow: 620,
  Condition.showerSnow: 621,
  Condition.heavyShowerSnow: 622,
  Condition.mist: 701,
  Condition.smoke: 711,
  Condition.haze: 721,
  Condition.sandDustWhirls: 731,
  Condition.fog: 741,
  Condition.sand: 751,
  Condition.dust: 761,
  Condition.volcanicAsh: 762,
  Condition.squalls: 771,
  Condition.tornado: 781,
  Condition.clear: 800,
  Condition.fewClouds: 801,
  Condition.scatteredClouds: 802,
  Condition.brokenClouds: 803,
  Condition.overcastClouds: 804,
};
